import { Organizer, DAVHut, Badge } from "@/types";

export const organizers: Organizer[] = [
  {
    id: "1",
    name: "Attila",
    role: "",
    image: "/images/team/attila.jpg",
    bio: "",
    },
  {
    id: "2",
    name: "Samu",
    role: "",
    image: "/images/team/samu.jpg",
    bio: "",
  },
  {
    id: "3",
    name: "Vrushabh",
    role: "",
    image: "/images/team/vru.jpg",
    bio: "",
    },
  {
    id: "4",
    name: "Andrea",
    role: "",
    image: "/images/team/andrea.jpg",
    bio: "",
    },
  {
    id: "5",
    name: "Julien",
    role: "",
    image: "/images/team/julien.jpg",
    bio: "",  },
  {
    id: "6",
    name: "Georgi",
    role: "",
    image: "/images/team/georgi.jpg",
    bio: "",
    },
  {
    id: "7",
    name: "Hoda",
    role: "",
    image: "/images/team/hoda.jpg",
    bio: "",
    },
  {
    id: "8",
    name: "Alex",
    role: "",
    image: "/images/team/alex.jpg",
    bio: "",
    },
];

export const davHuts: DAVHut[] = [
  {
    id: "1",
    name: "Knorrhütte",
    elevation: 2052,
    latitude: 47.4089,
    longitude: 11.0011,
    region: "Wetterstein",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Knorrhuette",
  },
  {
    id: "2",
    name: "Münchner Haus",
    elevation: 2964,
    latitude: 47.4211,
    longitude: 10.9854,
    region: "Zugspitze",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Muenchner-Haus",
  },
  {
    id: "3",
    name: "Rotwandhaus",
    elevation: 1737,
    latitude: 47.6544,
    longitude: 11.9386,
    region: "Mangfallgebirge",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Rotwandhaus",
  },
  {
    id: "4",
    name: "Blaueishütte",
    elevation: 1651,
    latitude: 47.5075,
    longitude: 12.8667,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Blaueis-Huette",
  },
  {
    id: "5",
    name: "Schneibsteinhaus",
    elevation: 1670,
    latitude: 47.5181,
    longitude: 12.9939,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Schneibsteinhaus",
  },
  {
    id: "6",
    name: "Wasseralm",
    elevation: 1416,
    latitude: 47.4694,
    longitude: 12.9361,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Wasseralm",
  },
  {
    id: "7",
    name: "Priener Hütte",
    elevation: 1410,
    latitude: 47.7239,
    longitude: 12.3461,
    region: "Chiemgau",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Priener-Huette",
  },
  {
    id: "8",
    name: "Brünnsteinhaus",
    elevation: 1360,
    latitude: 47.6633,
    longitude: 12.0833,
    region: "Mangfallgebirge",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Bruennsteinhaus",
  },
  {
    id: "9",
    name: "Tegernseer Hütte",
    elevation: 1650,
    latitude: 47.675,
    longitude: 11.7083,
    region: "Rofangebirge",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Tegernseer-Huette",
  },
  {
    id: "10",
    name: "Wimbachgrieshütte",
    elevation: 1327,
    latitude: 47.4861,
    longitude: 12.8939,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Wimbachgries-Huette",
  },
];

export const badges: Badge[] = [
  {
    id: "1",
    name: "The First Step",
    description: "Completed your first hike",
    icon: "footprints",
    earned: false,
  },
  {
    id: "2",
    name: "Trailblazer",
    description: "Completed 5+ hikes",
    icon: "flame",
    earned: false,
  },
  {
    id: "3",
    name: "Mountain Goat",
    description: "Completed a hard or expert hike",
    icon: "mountain",
    earned: false,
  },
  {
    id: "4",
    name: "Veteran",
    description: "Member for 6+ months",
    icon: "award",
    earned: false,
  },
];