import { Hike, Organizer, DAVHut, Badge } from "./types";

export const mockHikes: Hike[] = [
  {
    id: "1",
    name: "Partnachklamm Gorge",
    date: "2025-01-29",
    end_date: null,
    location_name: "Garmisch-Partenkirchen",
    location_lat: 47.4538,
    location_lng: 11.0809,
    difficulty: "easy",
    distance: 6,
    elevation: 200,
    duration: "3-4 hours",
    description:
      "Walk through the spectacular Partnachklamm gorge with its towering cliffs and rushing waters. Perfect for beginners!",
    image_url: "src/assets/attila.jpg",
    max_participants: 25,
    organizer_name: "Max Müller",
    organizer_id: null,
    status: "upcoming",
    created_at: "2024-12-01",
    updated_at: "2024-12-01",
    enrollment_count: 0,
  },
  {
    id: "2",
    name: "Königssee Lake Trail",
    date: "2025-01-22",
    end_date: null,
    location_name: "Berchtesgaden",
    location_lat: 47.5575,
    location_lng: 12.9759,
    difficulty: "moderate",
    distance: 12,
    elevation: 450,
    duration: "5-6 hours",
    description:
      "Explore the pristine Königssee lake surrounded by dramatic alpine peaks. A perfect blend of scenic beauty and moderate challenge.",
    image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    max_participants: 20,
    organizer_name: "Anna Schmidt",
    organizer_id: null,
    status: "upcoming",
    created_at: "2024-12-01",
    updated_at: "2024-12-01",
    enrollment_count: 0,
  },
  {
    id: "3",
    name: "Zugspitze Summit",
    date: "2025-01-15",
    end_date: "2025-01-16",
    location_name: "Garmisch-Partenkirchen",
    location_lat: 47.4211,
    location_lng: 10.9854,
    difficulty: "hard",
    distance: 18.5,
    elevation: 2200,
    duration: "2 days",
    description:
      "Conquer Germany's highest peak! This challenging hike takes you through stunning alpine scenery to the summit of the Zugspitze.",
    image_url: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800",
    max_participants: 15,
    organizer_name: "Thomas Bauer",
    organizer_id: null,
    status: "upcoming",
    created_at: "2024-12-01",
    updated_at: "2024-12-01",
    enrollment_count: 0,
  },
  {
    id: "4",
    name: "Eibsee Round Trail",
    date: "2024-11-12",
    end_date: null,
    location_name: "Grainau",
    location_lat: 47.4574,
    location_lng: 10.9697,
    difficulty: "easy",
    distance: 7,
    elevation: 100,
    duration: "2-3 hours",
    description: "A beautiful walk around the turquoise Eibsee lake with stunning views of the Zugspitze.",
    image_url: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800",
    max_participants: 30,
    organizer_name: "Lisa Weber",
    organizer_id: null,
    status: "completed",
    created_at: "2024-10-01",
    updated_at: "2024-10-01",
    enrollment_count: 22,
  },
];

export const mockOrganizers: Organizer[] = [
  {
    id: "1",
    name: "Attila",
    role: "",
    image: "src/assets/attila.jpg",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ex dui, sodales non rutrum ac.",
  },
  {
    id: "2",
    name: "Samu",
    role: "",
    image: "src/assets/samu.jpg",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ex dui, sodales non rutrum ac.",
  },
  {
    id: "3",
    name: "Vrushabh",
    role: "",
    image: "src/assets/vru.jpg",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ex dui, sodales non rutrum ac.",
  },
  {
    id: "4",
    name: "Andrea",
    role: "",
    image: "src/assets/andrea.jpg",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ex dui, sodales non rutrum ac.",
  },
  {
    id: "5",
    name: "Julien",
    role: "",
    image: "src/assets/julien.jpg",
    bio: "Certified mountain guide and first aid instructor. Ensures every hike is safe and enjoyable.",
  },
  {
    id: "6",
    name: "Georgi",
    role: "",
    image: "src/assets/georgi.jpg",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ex dui, sodales non rutrum ac.",
  },
];

export const davHuts: DAVHut[] = [
  {
    id: "1",
    name: "Knorrhütte",
    elevation: 2052,
    latitude: 47.4089,
    longitude: 11.0011,
    region: "Wetterstein",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Knorrhuette",
  },
  {
    id: "2",
    name: "Münchner Haus",
    elevation: 2964,
    latitude: 47.4211,
    longitude: 10.9854,
    region: "Zugspitze",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Muenchner-Haus",
  },
  {
    id: "3",
    name: "Rotwandhaus",
    elevation: 1737,
    latitude: 47.6544,
    longitude: 11.9386,
    region: "Mangfallgebirge",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Rotwandhaus",
  },
  {
    id: "4",
    name: "Blaueishütte",
    elevation: 1651,
    latitude: 47.5075,
    longitude: 12.8667,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Blaueis-Huette",
  },
  {
    id: "5",
    name: "Schneibsteinhaus",
    elevation: 1670,
    latitude: 47.5181,
    longitude: 12.9939,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Schneibsteinhaus",
  },
  {
    id: "6",
    name: "Wasseralm",
    elevation: 1416,
    latitude: 47.4694,
    longitude: 12.9361,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Wasseralm",
  },
  {
    id: "7",
    name: "Priener Hütte",
    elevation: 1410,
    latitude: 47.7239,
    longitude: 12.3461,
    region: "Chiemgau",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Priener-Huette",
  },
  {
    id: "8",
    name: "Brünnsteinhaus",
    elevation: 1360,
    latitude: 47.6633,
    longitude: 12.0833,
    region: "Mangfallgebirge",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Bruennsteinhaus",
  },
  {
    id: "9",
    name: "Tegernseer Hütte",
    elevation: 1650,
    latitude: 47.675,
    longitude: 11.7083,
    region: "Rofangebirge",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Tegernseer-Huette",
  },
  {
    id: "10",
    name: "Wimbachgrieshütte",
    elevation: 1327,
    latitude: 47.4861,
    longitude: 12.8939,
    region: "Berchtesgaden",
    link: "https://www.alpenverein.de/DAV-Services/Huettensuche/Wimbachgries-Huette",
  },
];

export const mockBadges: Badge[] = [
  {
    id: "1",
    name: "The First Step",
    description: "Completed your first hike",
    icon: "footprints",
    earned: false,
  },
  {
    id: "2",
    name: "Trailblazer",
    description: "Completed 5+ hikes",
    icon: "flame",
    earned: false,
  },
  {
    id: "3",
    name: "Mountain Goat",
    description: "Completed a hard or expert hike",
    icon: "mountain",
    earned: false,
  },
  {
    id: "4",
    name: "Veteran",
    description: "Member for 6+ months",
    icon: "award",
    earned: false,
  },
];
