
  create table "public"."planned_hikes_date" (
    "id" integer generated by default as identity not null,
    "date" date not null,
    "description" text default ''::text
      );


alter table "public"."planned_hikes_date" enable row level security;

CREATE UNIQUE INDEX planned_hikes_date_pkey ON public.planned_hikes_date USING btree (id);

alter table "public"."planned_hikes_date" add constraint "planned_hikes_date_pkey" PRIMARY KEY using index "planned_hikes_date_pkey";

grant delete on table "public"."planned_hikes_date" to "anon";

grant insert on table "public"."planned_hikes_date" to "anon";

grant references on table "public"."planned_hikes_date" to "anon";

grant select on table "public"."planned_hikes_date" to "anon";

grant trigger on table "public"."planned_hikes_date" to "anon";

grant truncate on table "public"."planned_hikes_date" to "anon";

grant update on table "public"."planned_hikes_date" to "anon";

grant delete on table "public"."planned_hikes_date" to "authenticated";

grant insert on table "public"."planned_hikes_date" to "authenticated";

grant references on table "public"."planned_hikes_date" to "authenticated";

grant select on table "public"."planned_hikes_date" to "authenticated";

grant trigger on table "public"."planned_hikes_date" to "authenticated";

grant truncate on table "public"."planned_hikes_date" to "authenticated";

grant update on table "public"."planned_hikes_date" to "authenticated";

grant delete on table "public"."planned_hikes_date" to "postgres";

grant insert on table "public"."planned_hikes_date" to "postgres";

grant references on table "public"."planned_hikes_date" to "postgres";

grant select on table "public"."planned_hikes_date" to "postgres";

grant trigger on table "public"."planned_hikes_date" to "postgres";

grant truncate on table "public"."planned_hikes_date" to "postgres";

grant update on table "public"."planned_hikes_date" to "postgres";

grant delete on table "public"."planned_hikes_date" to "service_role";

grant insert on table "public"."planned_hikes_date" to "service_role";

grant references on table "public"."planned_hikes_date" to "service_role";

grant select on table "public"."planned_hikes_date" to "service_role";

grant trigger on table "public"."planned_hikes_date" to "service_role";

grant truncate on table "public"."planned_hikes_date" to "service_role";

grant update on table "public"."planned_hikes_date" to "service_role";


  create policy "Admin manages planned dates"
  on "public"."planned_hikes_date"
  as permissive
  for all
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "Public view planned dates"
  on "public"."planned_hikes_date"
  as permissive
  for select
  to public
using (true);



